version: '3'
services:
  webserver-100:
    image: php-apt:latest
    ports:
      - "5671:80"
    volumes:
      - ./100/app:/var/www/html

  webserver-200:
    image: php-apt:latest
    ports:
      - "5672:80"
    volumes:
      - ./200/app:/var/www/html

  webserver-300:
    image: php-apt:latest
    ports:
      - "5673:80"
    volumes:
      - ./300/app:/var/www/html

  webserver-400:
    image: php-apt:latest
    ports:
      - "5674:80"
    volumes:
      - ./400/app:/var/www/html

  webserver-500:
    image: php-apt:latest
    ports:
      - "5675:80"
    volumes:
      - ./500/app/index.php:/var/www/html/index.php
      - ./500/app/flag.txt:/var/www/root/flag.txt


  


